<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AssetManagementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assetManagement = [
            // Ahmed Hassan Khan - Senior Developer (Multiple assets)
            [
                'employee_id' => 1,
                'asset_type' => 'laptop',
                'asset_name' => 'MacBook Pro 16-inch',
                'model' => 'MacBook Pro M2',
                'serial_number' => 'MBP-2023-001',
                'issued_date' => '2020-01-20',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 350000.00,
                'notes' => 'High-performance laptop for development work',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 1,
                'asset_type' => 'monitor',
                'asset_name' => '27-inch 4K Monitor',
                'model' => 'Dell UltraSharp U2720Q',
                'serial_number' => 'MON-2023-001',
                'issued_date' => '2020-01-20',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 65000.00,
                'notes' => 'Primary display for development',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 1,
                'asset_type' => 'phone',
                'asset_name' => 'iPhone 14 Pro',
                'model' => 'iPhone 14 Pro',
                'serial_number' => 'IPH-2023-001',
                'issued_date' => '2022-07-15',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 180000.00,
                'notes' => 'Company phone for senior developer',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Fatima Ali Sheikh - HR Manager
            [
                'employee_id' => 2,
                'asset_type' => 'laptop',
                'asset_name' => 'Dell XPS 15',
                'model' => 'Dell XPS 15 9520',
                'serial_number' => 'DEL-2023-001',
                'issued_date' => '2019-03-25',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 280000.00,
                'notes' => 'Primary laptop for HR management tasks',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 2,
                'asset_type' => 'phone',
                'asset_name' => 'Samsung Galaxy S23',
                'model' => 'Galaxy S23 Ultra',
                'serial_number' => 'SAM-2023-001',
                'issued_date' => '2021-09-20',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 165000.00,
                'notes' => 'Company phone for HR Manager',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 2,
                'asset_type' => 'tablet',
                'asset_name' => 'iPad Air',
                'model' => 'iPad Air 5th Gen',
                'serial_number' => 'IPA-2023-001',
                'issued_date' => '2022-01-15',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 95000.00,
                'notes' => 'For presentations and mobile work',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Muhammad Usman Malik - Marketing Manager
            [
                'employee_id' => 3,
                'asset_type' => 'laptop',
                'asset_name' => 'MacBook Air M2',
                'model' => 'MacBook Air M2',
                'serial_number' => 'MBA-2023-001',
                'issued_date' => '2018-07-05',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 220000.00,
                'notes' => 'Marketing and design work',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'asset_type' => 'phone',
                'asset_name' => 'iPhone 13',
                'model' => 'iPhone 13 Pro',
                'serial_number' => 'IPH-2022-001',
                'issued_date' => '2021-01-10',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 155000.00,
                'notes' => 'Company phone for marketing manager',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'asset_type' => 'camera',
                'asset_name' => 'Canon EOS R6',
                'model' => 'Canon EOS R6 Mark II',
                'serial_number' => 'CAM-2023-001',
                'issued_date' => '2021-06-15',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 450000.00,
                'notes' => 'For marketing content creation and events',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Ayesha Iqbal Chaudhry - Accountant
            [
                'employee_id' => 4,
                'asset_type' => 'laptop',
                'asset_name' => 'HP EliteBook 840',
                'model' => 'HP EliteBook 840 G9',
                'serial_number' => 'HP-2023-001',
                'issued_date' => '2022-05-15',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 185000.00,
                'notes' => 'Accounting and finance work',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 4,
                'asset_type' => 'calculator',
                'asset_name' => 'HP 12C Financial Calculator',
                'model' => 'HP 12C Platinum',
                'serial_number' => 'CALC-2023-001',
                'issued_date' => '2022-05-15',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 15000.00,
                'notes' => 'Financial calculations',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Zain Abbas Bukhari - Support Agent
            [
                'employee_id' => 5,
                'asset_type' => 'laptop',
                'asset_name' => 'Lenovo ThinkPad E15',
                'model' => 'ThinkPad E15 Gen 4',
                'serial_number' => 'LEN-2023-001',
                'issued_date' => '2023-02-05',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 125000.00,
                'notes' => 'Basic laptop for support work',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 5,
                'asset_type' => 'headset',
                'asset_name' => 'Logitech H390',
                'model' => 'H390 USB Headset',
                'serial_number' => 'HEAD-2023-001',
                'issued_date' => '2023-02-05',
                'return_date' => null,
                'condition_when_issued' => 'new',
                'condition_when_returned' => null,
                'purchase_value' => 8000.00,
                'notes' => 'Customer support calls',
                'status' => 'issued',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Some returned assets (examples)
            [
                'employee_id' => 1,
                'asset_type' => 'laptop',
                'asset_name' => 'MacBook Pro 13-inch (Old)',
                'model' => 'MacBook Pro Intel',
                'serial_number' => 'MBP-2020-001',
                'issued_date' => '2020-01-20',
                'return_date' => '2023-01-15',
                'condition_when_issued' => 'new',
                'condition_when_returned' => 'good',
                'purchase_value' => 280000.00,
                'notes' => 'Upgraded to newer model',
                'status' => 'returned',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'asset_type' => 'phone',
                'asset_name' => 'iPhone 11 (Old)',
                'model' => 'iPhone 11 Pro',
                'serial_number' => 'IPH-2019-001',
                'issued_date' => '2021-01-10',
                'return_date' => '2022-01-10',
                'condition_when_issued' => 'new',
                'condition_when_returned' => 'fair',
                'purchase_value' => 135000.00,
                'notes' => 'Replaced with newer model, minor scratches',
                'status' => 'returned',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('asset_management')->insert($assetManagement);
    }
}
