<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CompensationHistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $compensationHistory = [
            // Ahmed Hassan Khan - Multiple salary changes
            [
                'employee_id' => 1,
                'effective_date' => '2020-01-15',
                'action_type' => 'joining',
                'new_salary' => 45000.00,
                'previous_salary' => null,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => null,
                'remarks' => 'Initial joining salary',
                'approved_by' => 'HR Department',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 1,
                'effective_date' => '2021-01-15',
                'action_type' => 'increment',
                'new_salary' => 55000.00,
                'previous_salary' => 45000.00,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => 10000.00,
                'remarks' => 'Annual increment - good performance',
                'approved_by' => 'Sarah Ahmed',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 1,
                'effective_date' => '2022-07-01',
                'action_type' => 'promotion',
                'new_salary' => 75000.00,
                'previous_salary' => 55000.00,
                'bonus_amount' => 15000.00,
                'incentive_amount' => null,
                'adjustment_amount' => 20000.00,
                'remarks' => 'Promoted to Senior Developer',
                'approved_by' => 'Sarah Ahmed',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 1,
                'effective_date' => '2023-01-15',
                'action_type' => 'increment',
                'new_salary' => 85000.00,
                'previous_salary' => 75000.00,
                'bonus_amount' => null,
                'incentive_amount' => 5000.00,
                'adjustment_amount' => 10000.00,
                'remarks' => 'Annual increment with performance incentive',
                'approved_by' => 'Sarah Ahmed',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Fatima Ali Sheikh
            [
                'employee_id' => 2,
                'effective_date' => '2019-03-20',
                'action_type' => 'joining',
                'new_salary' => 40000.00,
                'previous_salary' => null,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => null,
                'remarks' => 'Initial joining salary as HR Assistant',
                'approved_by' => 'Nadia Khan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 2,
                'effective_date' => '2020-03-20',
                'action_type' => 'increment',
                'new_salary' => 52000.00,
                'previous_salary' => 40000.00,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => 12000.00,
                'remarks' => 'First annual increment - excellent performance',
                'approved_by' => 'Nadia Khan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 2,
                'effective_date' => '2021-09-15',
                'action_type' => 'promotion',
                'new_salary' => 80000.00,
                'previous_salary' => 52000.00,
                'bonus_amount' => 20000.00,
                'incentive_amount' => null,
                'adjustment_amount' => 28000.00,
                'remarks' => 'Promoted to HR Manager',
                'approved_by' => 'Nadia Khan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 2,
                'effective_date' => '2023-03-20',
                'action_type' => 'increment',
                'new_salary' => 95000.00,
                'previous_salary' => 80000.00,
                'bonus_amount' => null,
                'incentive_amount' => 8000.00,
                'adjustment_amount' => 15000.00,
                'remarks' => 'Annual increment with leadership bonus',
                'approved_by' => 'Nadia Khan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Muhammad Usman Malik
            [
                'employee_id' => 3,
                'effective_date' => '2018-07-01',
                'action_type' => 'joining',
                'new_salary' => 50000.00,
                'previous_salary' => null,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => null,
                'remarks' => 'Initial joining salary as Marketing Executive',
                'approved_by' => 'Ali Hassan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'effective_date' => '2019-07-01',
                'action_type' => 'increment',
                'new_salary' => 65000.00,
                'previous_salary' => 50000.00,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => 15000.00,
                'remarks' => 'First year increment - exceeded targets',
                'approved_by' => 'Ali Hassan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'effective_date' => '2021-01-01',
                'action_type' => 'promotion',
                'new_salary' => 90000.00,
                'previous_salary' => 65000.00,
                'bonus_amount' => 25000.00,
                'incentive_amount' => null,
                'adjustment_amount' => 25000.00,
                'remarks' => 'Promoted to Marketing Manager',
                'approved_by' => 'Ali Hassan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 3,
                'effective_date' => '2022-07-01',
                'action_type' => 'increment',
                'new_salary' => 110000.00,
                'previous_salary' => 90000.00,
                'bonus_amount' => null,
                'incentive_amount' => 12000.00,
                'adjustment_amount' => 20000.00,
                'remarks' => 'Merit increase with quarterly incentive',
                'approved_by' => 'Ali Hassan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Ayesha Iqbal Chaudhry
            [
                'employee_id' => 4,
                'effective_date' => '2022-05-10',
                'action_type' => 'joining',
                'new_salary' => 42000.00,
                'previous_salary' => null,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => null,
                'remarks' => 'Initial joining salary as Junior Accountant',
                'approved_by' => 'Tariq Mahmood',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'employee_id' => 4,
                'effective_date' => '2023-05-10',
                'action_type' => 'promotion',
                'new_salary' => 62000.00,
                'previous_salary' => 42000.00,
                'bonus_amount' => 8000.00,
                'incentive_amount' => null,
                'adjustment_amount' => 20000.00,
                'remarks' => 'Promoted to Accountant after excellent first year',
                'approved_by' => 'Tariq Mahmood',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Zain Abbas Bukhari
            [
                'employee_id' => 5,
                'effective_date' => '2023-02-01',
                'action_type' => 'joining',
                'new_salary' => 38000.00,
                'previous_salary' => null,
                'bonus_amount' => null,
                'incentive_amount' => null,
                'adjustment_amount' => null,
                'remarks' => 'Initial joining salary as Support Agent - Part Time',
                'approved_by' => 'Sana Malik',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('compensation_history')->insert($compensationHistory);
    }
}
